package structs

const (
	TH_WEB_NO_TOKEN  = "TH_WEB_NO_TOKEN"
	TH_WEB_JSON_FAIL = "TH_WEB_JSON_FAIL"
	TH_WEB_IMG_FAIL  = "TH_WEB_IMG_FAIL"

	TH_BOT_INVALID_TOKEN = "Not Found"
	TH_BOT_MESSAGE_FAIL  = "TH_BOT_MESSAGE_FAIL"
)
